# Generated by Django 4.0.2 on 2022-02-06 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(max_length=200, verbose_name='Type')),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('accepted', 'Accepted'), ('paid', 'Payment'), ('activated', 'Activated'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=30)),
                ('sum_insured', models.FloatField(verbose_name='Sum insured in Policy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quote',
            },
        ),
        migrations.CreateModel(
            name='UserPolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('accepted', 'Accepted'), ('paid', 'Payment'), ('activated', 'Activated'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='policy.quote')),
            ],
            options={
                'verbose_name': 'Policy History',
                'verbose_name_plural': 'Policies Histories',
                'db_table': 'policy_history',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='policy.quote')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policy',
            },
        ),
    ]
